-- Справочник названий компаний
CREATE TABLE companies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL UNIQUE 
);

-- Справочник способов закупки (Адресный запрос котировок, Аккредитация и т.д)
CREATE TABLE procurement_methods (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name VARCHAR(100) NOT NULL UNIQUE
);

-- Справочник электронных площадок
CREATE TABLE platforms (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_name VARCHAR(50) NOT NULL UNIQUE 
);

-- Справочник категорий (Безопсность, Питание и вода и т.д)
CREATE TABLE procurement_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(50) NOT NULL UNIQUE 
);

-- Справочник статуса закупки (Архив, сбор заявок и т.д)
CREATE TABLE procurement_status (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL UNIQUE
);


-- Основная таблица с процедурами
CREATE TABLE procurement (
    procedure_code VARCHAR(30) PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE RESTRICT,
    method_id INT REFERENCES pocurement_methods(id) ON DELETE RESTRICT,
    platform_id INT REFERENCES platforms(id) ON DELETE RESTRICT,
    type_id INT REFERENCES pocurement_types(id) ON DELETE RESTRICT,
    status_id INT REFERENCES procurement_status(id) ON DELETE RESTRICT,

    title TEXT NOT NULL,
    initial_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(3) NOT NULL DEFAULT 'RUB',

    published_at DATE NOT NULL,
    deadline_at DATE,
    results_at DATE
);